#Orden en el que se ejecutan las excepciones

def defecto(nombre):
    try: #Ejectua el codigo
    
    except: #Si falla
    
    else: #Si no da fallo
    
    finally: #Se ejecuta siempre 
        
    pass